/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.android.rings_extended;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int icon_more=0x7f020001;
        public static final int now_playing=0x7f020002;
        public static final int scrollbar_handle_accelerated_anim2=0x7f020003;
    }
    public static final class id {
        public static final int cancelButton=0x7f050009;
        public static final int duration=0x7f05000a;
        public static final int icon=0x7f050000;
        public static final int line1=0x7f05000b;
        public static final int line2=0x7f05000c;
        public static final int listContainer=0x7f050007;
        public static final int more=0x7f050005;
        public static final int okayButton=0x7f050008;
        public static final int play_indicator=0x7f05000d;
        public static final int progressContainer=0x7f050006;
        public static final int radio=0x7f050001;
        public static final int textDouble1=0x7f050003;
        public static final int textDouble2=0x7f050004;
        public static final int textSingle=0x7f050002;
    }
    public static final class layout {
        public static final int list_item=0x7f030000;
        public static final int music_picker=0x7f030001;
        public static final int rings_extended=0x7f030002;
        public static final int track_list_item=0x7f030003;
    }
    public static final class string {
        /**  Characters that are used for each of the fast-scroll widget that skips directly
         to names starting with this letter.  If your language sorts differently than this,
         please rearrange the alphabet here to be whatever is correct (e.g. Norwegian
         has the three additional letters at the end). 
         */
        public static final int alphabet=0x7f04000e;
        public static final int appName=0x7f040000;
        public static final int defaultRingtoneLabel=0x7f040002;
        /** 
    This string is used as the format string in a String.format call,
    and 5 additional arguments are available for printing:
    1 - hours
    2 - minutes
    3 - minutes%60
    4 - seconds
    5 - second%60
    
         */
        public static final int durationformat=0x7f04000d;
        public static final int existingRingtoneLabel=0x7f040003;
        public static final int loading=0x7f040006;
        public static final int musicPickerName=0x7f040004;
        public static final int musicPickerTitle=0x7f040005;
        public static final int noMusic=0x7f040007;
        public static final int silentLabel=0x7f040001;
        public static final int sortByAlbum=0x7f040009;
        public static final int sortByArtist=0x7f04000a;
        public static final int sortByTrack=0x7f040008;
        public static final int unknownAlbumName=0x7f04000c;
        public static final int unknownArtistName=0x7f04000b;
    }
}
