/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.example.amazed;

public final class R {
    public static final class array {
        public static final int gameStrings=0x7f040000;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int exit=0x7f020000;
        public static final int icon=0x7f020001;
        public static final int path=0x7f020002;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
    }
}
