/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.google.android.divideandconquer;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ball=0x7f020000;
        public static final int ballsicon=0x7f020001;
        public static final int explosion1=0x7f020002;
        public static final int explosion2=0x7f020003;
        public static final int explosion3=0x7f020004;
    }
    public static final class id {
        public static final int ballsView=0x7f050005;
        public static final int levelInfo=0x7f050002;
        public static final int livesLeft=0x7f050004;
        public static final int newGame=0x7f050000;
        public static final int percentContained=0x7f050003;
        public static final int quit=0x7f050001;
    }
    public static final class layout {
        public static final int game_over_dialog=0x7f030000;
        public static final int main=0x7f030001;
        public static final int welcome_dialog=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int game_over=0x7f040002;
        public static final int instructions=0x7f040003;
        public static final int level=0x7f040006;
        public static final int lives_left=0x7f040008;
        public static final int new_game=0x7f040001;
        public static final int one_life_left=0x7f040007;
        public static final int percent_contained=0x7f040005;
        public static final int quit=0x7f040004;
        public static final int settings_difficulty=0x7f04000c;
        public static final int settings_difficulty_summary=0x7f04000d;
        public static final int settings_five_lives=0x7f04000e;
        public static final int settings_one_life=0x7f040010;
        public static final int settings_three_lives=0x7f04000f;
        public static final int settings_vibrate=0x7f04000a;
        public static final int settings_vibrate_summary=0x7f04000b;
        public static final int unpause_instructions=0x7f040009;
    }
}
